# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='days_duration',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='nights_duration',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
    ]
