# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplor', '0002_auto_20161004_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
