# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplor', '0003_itinerary_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='location',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
