# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:08
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplor', '0004_auto_20161017_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='primary_image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
